- name: Build with CMake
  shell: cmd
  env:
    ENV_VCVARSALL: ${{ env.vcvarsall-path }}
    ENV_QT_PATH: ${{ env.qt-install-path }}\${{ env.qt-ver }}\${{ matrix.qt-arch-install }}
  run: |
    rem call python ci\generate-version.py
    call "%ENV_VCVARSALL%" ${{ matrix.msvc-arch }}
    if not exist build mkdir build
    cd build
    cmake .. -G "Visual Studio 17 2022" -A ${{ matrix.msvc-arch }} ^
      -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
      -DCMAKE_PREFIX_PATH="%ENV_QT_PATH%" ^
      -DQT_DIR="%QT_DIR%" ^
      -DQt5_DIR="%Qt5_DIR%"
    cmake --build . --config RelWithDebInfo
    cd ..
